### ISSUE TITLE
error random_sample.py CUDA out of memory

### ISSUE THREAD

**Issue by molo32** [iyttor/GPNN#3]
cuda initialized!
Traceback (most recent call last):
  File "/content/GPNN/random_sample.py", line 11, in <module>
    model.run()
  File "/content/GPNN/model/gpnn.py", line 99, in run
    self.ALPHA)
  File "/content/GPNN/model/gpnn.py", line 114, in PNN
    dist = compute_distances(queries, keys)
  File "/content/GPNN/model/gpnn.py", line 159, in compute_distances
    dist_mat = torch.zeros((queries.shape[0], keys.shape[0]), dtype=torch.float16, device=device)
RuntimeError: CUDA out of memory. Tried to allocate 20.67 GiB (GPU 0; 14.76 GiB total capacity; 354.41 MiB already allocated; 7.29 GiB free; 6.42 GiB reserved in total by PyTorch)

**Comment by iyttor** [comment]
Your resources are limited (GPU's RAM).
You may consider constructing smaller image by specifying '--out_size=SMALL_HEIGHT_PX', or specifying '--faiss' after installing faiss (look in the main readme).
